---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_latest
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
  connection_options:
    ansible_connection: community.docker.docker_api
