---
- name: Vector block
  block:
    - name: Create user for vector
      ansible.builtin.user:
        name: vector
        shell: /sbin/nologin
        state: present
        create_home: true
    - name: Get Vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "/home/vector/vector-{{ vector_version }}.tar.gz"
        mode: "0644"
    - name: Create directory for Vector
      ansible.builtin.file:
        path: /opt/vector
        state: directory
        owner: vector
        group: vector
        mode: "0755"
    - name: Create directory for Vector data
      ansible.builtin.file:
        path: /opt/vector/data
        state: directory
        owner: vector
        group: vector
        mode: "0755"
    - name: Extract Vector
      ansible.builtin.unarchive:
        src: "/home/vector/vector-{{ vector_version }}.tar.gz"
        dest: /opt/vector
        owner: vector
        group: vector
        extra_opts: [--strip-components=2]
        remote_src: true
    - name: Generate systemd unit (Vector)
      ansible.builtin.template:
        src: vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: "0644"
    - name: Generate Vector config
      ansible.builtin.template:
        src: vector.yml.j2
        dest: "/opt/vector/config/vector.yml"
        owner: vector
        group: vector
        mode: "0664"
      notify: Start Vector service
  become: true
